objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dependents</relationshipLabel>
        <relationshipName>Accounts9</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recording__c.object
<CustomObject>
    <fields>
        <fullName>Dropbox_URL__c</fullName>
        <description>The primary Dropbox storage location for Recordings. Privileges must be granted in Dropbox to access.</description>
        <label>Dropbox URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Primary Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recordings</relationshipLabel>
        <relationshipName>Recordings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Recording_Source__c</fullName>
        <label>Recording Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RingCentral</fullName>
                </value>
                <value>
                    <fullName>Verification</fullName>
                </value>
                <value>
                    <fullName>Vicidial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>S3_URL__c</fullName>
        <description>The URL to the redundant S3 storage bucket. S3 privileges are required to access the recording.</description>
        <label>S3 URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Recording</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Recording Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recordings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordingInsertTest.cls
@isTest(seealldata = false)
public class RecordingInsertTest { 
    
    @isTest
    public static void testRecordingDependentAccountTest() {

        Test.startTest();

        String parentRecordType;

        String dependentRecordType;
        
        List<RecordType> accountRecordTypes = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Account'];

        for(RecordType recordTypeInfo : accountRecordTypes) {
            if(recordTypeInfo.Name == 'Dependent') {
                dependentRecordType = recordTypeInfo.Id;
            }
            else if (recordTypeInfo.Name == 'Primary Member') {
                parentRecordType = recordTypeInfo.Id;
            }
        }

        Account testParentAccount = new Account(LastName = 'Recording Test Person Account', 
                                                RecordTypeId = parentRecordType,
                                                Phone = '123456');

        insert testParentAccount;

        Account testDependentAccount = new Account(LastName = 'Recording Test Person Account', 
                                                   Account__c = testParentAccount.Id,
                                                   RecordTypeId = dependentRecordType,
                                                   Phone = '234567');

        insert testDependentAccount;

        Recording__c testRecording = new Recording__c(Phone__c = '234567',
                                                      S3_URL__c = 'Test1',
                                                      Dropbox_URL__c = 'Test1',
                                                      Recording_Source__c = 'RingCentral');
        insert testRecording;

        testRecording = [SELECT Id, Member_Account__c FROM Recording__c WHERE Phone__c = '234567'];

        System.assertEquals(testParentAccount.Id, testRecording.Member_Account__c);
        Test.stopTest();
    }

    @isTest
    public static void testRecordingParentAccountTest() {

        Test.startTest();

        String parentRecordType;
        
        List<RecordType> accountRecordTypes = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Account'];

        for(RecordType recordTypeInfo : accountRecordTypes) {
            if(recordTypeInfo.Name == 'Primary Member') {
                parentRecordType = recordTypeInfo.Id;
            }
        }

        Account testParentAccount = new Account(LastName = 'Recording Test Person Account',
                                                RecordTypeId = parentRecordType,
                                                Phone = '123456');

        insert testParentAccount;

        Recording__c testRecording = new Recording__c(Phone__c = '123456',
                                                      S3_URL__c = 'Test2',
                                                      Dropbox_URL__c = 'Test2',
                                                      Recording_Source__c = 'RingCentral');
        insert testRecording;

        testRecording = [SELECT Id, Member_Account__c FROM Recording__c WHERE Phone__c = '123456'];

        System.assertEquals(testParentAccount.Id, testRecording.Member_Account__c);
        Test.stopTest();
    }
}