objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dependents</relationshipLabel>
        <relationshipName>Accounts9</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recording__c.object
<CustomObject>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Primary Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recordings</relationshipLabel>
        <relationshipName>Recordings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Recording</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Recording Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recordings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RecordingTriggerHelper.cls
public class RecordingTriggerHelper {
    public static void setAccountInformation(List<Recording__c> newRecordings) {
        Set<String> newPhoneNumbers = new Set<String>();
        for(Recording__c newRecording : newRecordings) {
            newPhoneNumbers.add(newRecording.Phone__c);
        }
        
    List<Account> accounts = [SELECT Id, RecordType.Name, Account__c, Phone
                              FROM Account
                              WHERE IsPersonAccount = true AND
                                    Phone IN :newPhoneNumbers];	
        
    // With Map --> works for dataload of hundreds of recordings insert at a time
    Map<String, Id> phoneToAccountId = new Map<String, Id>();

    for(Account accountInfo : accounts) {
        if(accountInfo.RecordType.Name == 'Dependent') {
            phoneToAccountId.put(accountInfo.Phone, accountInfo.Account__c);
        }
        else {
            phoneToAccountId.put(accountInfo.Phone, accountInfo.Id);
        }
    }

    for(Recording__c newRecording : newRecordings) {
        if(phoneToAccountId != null && phoneToAccountId.containsKey(newRecording.Phone__c)) {
            newRecording.Member_Account__c = phoneToAccountId.get(newRecording.Phone__c);
        }
    }
    }       
}