objects/ChargentOrders__ChargentOrder__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to Asset for know the Orders and Payment from &quot;Chargent App&quot;</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Chargent Orders</relationshipLabel>
        <relationshipName>Chargent_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the Account to which this Order is related.This shows the Account record this order was created for or used by. This field may be populated manually, as well as automateically when an order is created by using the Payment Console or Payment Request from Chargent Anywhere when configured on the Account object.</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Chargent Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Charge_Amount__c</fullName>
        <description>The amount to be authorized or charged by the next transaction. If there are multiple charges, this field will automatically reflect the Amount of the order minus the total amount of successful charges.</description>
        <inlineHelpText>The amount to be authorized or charged by the next transaction. If there are multiple charges, this field will automatically reflect the Amount of the order minus the total amount of successful charges.</inlineHelpText>
        <label>Charge Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Charge_Date__c</fullName>
        <description>This field displays the day of the month on which this recurring order collects payment.

The Chargent batch looks at the last transaction that is marked as recurring then charges again based on the frequency.  This caused slippage when there is a late payment.   

E.g., If a customer late pays by 11 days 3 months in a row, without Charge Date set you would miss a month&apos;s payment.   With Charge date set, the payment source will be charged the following month on the day of month set in this field.</description>
        <inlineHelpText>This field is the day of the month that Chargent will attempt the recurring transaction</inlineHelpText>
        <label>Charge Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentOrders__Manual_Charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to authorize or charge an amount different than the amount due on the order. This will prevent the &quot;Charge Amount&quot; from being automatically calculated and updated.</description>
        <inlineHelpText>Check this box when you want to authorize or charge an amount different than the amount due on the order. This will prevent the &quot;Charge Amount&quot; from being automatically calculated and updated.</inlineHelpText>
        <label>Manual Charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Order_Note__c</fullName>
        <description>allow users to type a short note</description>
        <label>Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Payment_End_Date__c</fullName>
        <description>When the Payment Stop rule of &quot;Date&quot; is slected, this field determins the date on which this recurring order will stop.</description>
        <inlineHelpText>If &quot;Payment Stop&quot; is set to &quot;Date&quot; please enter the date when the payments will stop</inlineHelpText>
        <label>Payment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Payment_Frequency__c</fullName>
        <description>The frequency on which this recurring order will collect payments. 
E.g., Daily, Weekly, Monthly.</description>
        <inlineHelpText>Once - Single time
Daily - Each day
Weekly - Every 7 days
Monthly - Monthly same date
Bimonthly - Every 2nd mo. same date
Quarterly - Every 4th mo. same date
Semiannual - Every 6th mo. same date
Annual - Same date each year
Biennial-  2 years</inlineHelpText>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Once</fullName>
                    <default>true</default>
                    <label>Once</label>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Biweekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Bimonthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semiannual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Biennial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentOrders__Payment_Start_Date__c</fullName>
        <description>Chargent will not attempt to charge this record until the Start Date</description>
        <inlineHelpText>Chargent will not attempt to charge this record until the Start Date</inlineHelpText>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ChargentOrders__Payment_Status__c</fullName>
        <description>Reflects the status of this order. For instance, recurring orders will show &quot;Recurring.&quot; Orders in collections status will show &quot;Automated Collection.&quot; Recurring orders that have failed and AREN&apos;T in collections will show &quot;Error.&quot;</description>
        <label>Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Stopped</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Automated Collection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentOrders__Payment_Stop__c</fullName>
        <description>This field determins the stop-rule for a recurring order.
DATE = Recurring schedule stops on a specific date
COUNT = Recurring schedule stops after a specific number of charges completes
BALANCE DUE = Recurring schedule stops after a specific amount has been reached
UNENDING = Recurring schedule doesn&apos;t stop unless manually stopped</description>
        <label>Payment Stop</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ChargentOrders__Payment_Frequency__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Count</fullName>
                </value>
                <value>
                    <fullName>Balance Due</fullName>
                </value>
                <value>
                    <fullName>Unending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentOrders__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ChargentOrders__Subtotal__c</fullName>
        <description>The subtotal is the amount due before taxes, shipping, or other fees are added to the order.</description>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Chargent Orders</relationshipLabel>
        <relationshipName>Chargent_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chargent Order</label>
    <nameField>
        <displayFormat>ORD-{000000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chargent Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OSH_ChargentOrdersTest.cls
@isTest
public class OSH_ChargentOrdersTest {

    @testSetup
    public static void setup() {
           //Create Account
           RecordType rtAcct = [SELECT Id from RecordType WHERE SobjectType = 'Account' limit 1];
           Account acc= new Account(Name = 'Test Account', RecordType = rtAcct);
           insert acc;
   
           //Create Asset
           Asset ass = new Asset(Name= 'AssetTest');
           insert ass;
   
           //Create Opp
           Opportunity opp = new Opportunity (Name = 'Opp Name', StageName= 'Prospecting', CloseDate = Date.newInstance(2024, 12, 9));
           insert opp;
   
           //Create Quote
           Quote qu = new Quote(Name= 'Quote Test', OpportunityId = opp.Id); 
           insert qu;
   
           //Create Chargent Order
           ChargentOrders__ChargentOrder__c newChargentOrder = new ChargentOrders__ChargentOrder__c();
           newChargentOrder.ChargentOrders__Account__c= acc.Id;
           newChargentOrder.Asset__c= ass.Id;
           newChargentOrder.ChargentOrders__Payment_Stop__c= 'Date';
           newChargentOrder.ChargentOrders__Charge_Amount__c= 89237923;
           newChargentOrder.ChargentOrders__Subtotal__c= 78;
           newChargentOrder.ChargentOrders__Charge_Date__c= '01';
           newChargentOrder.ChargentOrders__Order_Note__c= 'test test test';
           newChargentOrder.ChargentOrders__Manual_Charge__c= false;
           newChargentOrder.ChargentOrders__Payment_End_Date__c= Date.newInstance(2024, 04, 12);
           newChargentOrder.ChargentOrders__Payment_Frequency__c= 'Once';
           newChargentOrder.ChargentOrders__Payment_Status__c= 'Stopped';
           newChargentOrder.ChargentOrders__Payment_Start_Date__c= Date.newInstance(2023, 04, 12);
           newChargentOrder.ChargentOrders__Status__c= 'Initiated';
           newChargentOrder.Quote__c= qu.Id;
           insert newChargentOrder;
     
    }

    @isTest
    static void createChargentOrdersTest1() {

        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Asset ass = [SELECT Id FROM Asset WHERE Name = 'AssetTest'];
        Quote qu = [SELECT Id FROM Quote WHERE Name = 'Quote Test'];
        ChargentOrders__ChargentOrder__c newChargentOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c WHERE ChargentOrders__Account__c=: acc.Id ];
   
    	Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        //Fill input
        Map<String, Object> selectedMonthlyContributionDiscount = new Map<String,Object>();
        selectedMonthlyContributionDiscount.put('Recurrency', 'Forever');
        Map<String, Object> bill =new Map<String, Object>();
        String datebill = Datetime.now().format('yyyy-MM-dd');
        bill.put('billingDatePlan', datebill);
        Double formulaCont = 093820283;
        bill.put('FormulaContributionAmount', formulaCont);
        bill.put('FormulaContributionAmountWithPromotions', 98989);

        inputMap.put('bill', bill);
        inputMap.put('selectedMonthlyContributionDiscount', selectedMonthlyContributionDiscount);
        inputMap.put('chargentOrderId', newChargentOrder.Id);
        inputMap.put('AssetId', ass.Id);
        inputMap.put('incomingQuoteId', qu.Id);

        OSH_ChargentOrders ins = new OSH_ChargentOrders();
        Boolean ret = ins.invokeMethod('createChargentOrders', inputMap, outMap, options);
        System.assertEquals(true, ret);
    }

    @isTest
    static void createChargentOrdersForeverTest2() {

        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Asset ass = [SELECT Id FROM Asset WHERE Name = 'AssetTest'];
        Quote qu = [SELECT Id FROM Quote WHERE Name = 'Quote Test'];
        ChargentOrders__ChargentOrder__c newChargentOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c WHERE ChargentOrders__Account__c=: acc.Id ];
   
    	Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        //Fill input
        Map<String, Object> selectedMonthlyContributionDiscount = new Map<String,Object>();
        selectedMonthlyContributionDiscount.put('Recurrency', '1,2,3');
        Map<String, Object> bill =new Map<String, Object>();
        String datebill = Datetime.now().format('yyyy-MM-dd');
        bill.put('billingDatePlan', datebill);
        Double formulaCont = 093820283;
        bill.put('FormulaContributionAmount', formulaCont);
        bill.put('FormulaContributionAmountWithPromotions', 98989);

        inputMap.put('bill', bill);
        inputMap.put('selectedMonthlyContributionDiscount', selectedMonthlyContributionDiscount);
        inputMap.put('chargentOrderId', newChargentOrder.Id);
        inputMap.put('AssetId', ass.Id);
        inputMap.put('incomingQuoteId', qu.Id);

        OSH_ChargentOrders ins = new OSH_ChargentOrders();
        Boolean ret = ins.invokeMethod('createChargentOrders', inputMap, outMap, options);
        System.assertEquals(true, ret);
    }

    @isTest
    static void createChargentOrdersForeverTest3() {

        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Asset ass = [SELECT Id FROM Asset WHERE Name = 'AssetTest'];
        Quote qu = [SELECT Id FROM Quote WHERE Name = 'Quote Test'];
        ChargentOrders__ChargentOrder__c newChargentOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c WHERE ChargentOrders__Account__c=: acc.Id ];
   
    	Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        //Fill input
        Map<String, Object> selectedMonthlyContributionDiscount = new Map<String,Object>();
        selectedMonthlyContributionDiscount.put('Recurrency', '4');
        Map<String, Object> bill =new Map<String, Object>();
        String datebill = Datetime.now().format('yyyy-MM-dd');
        bill.put('billingDatePlan', datebill);
        Double formulaCont = 093820283;
        bill.put('FormulaContributionAmount', formulaCont);
        bill.put('FormulaContributionAmountWithPromotions', 98989);

        inputMap.put('bill', bill);
        inputMap.put('selectedMonthlyContributionDiscount', selectedMonthlyContributionDiscount);
        inputMap.put('chargentOrderId', newChargentOrder.Id);
        inputMap.put('AssetId', ass.Id);
        inputMap.put('incomingQuoteId', qu.Id);

        OSH_ChargentOrders ins = new OSH_ChargentOrders();
        Boolean ret = ins.invokeMethod('createChargentOrders', inputMap, outMap, options);
        System.assertEquals(true, ret);
    }

    @isTest
    static void createChargentOrdersForeverTest4() {

        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Asset ass = [SELECT Id FROM Asset WHERE Name = 'AssetTest'];
        Quote qu = [SELECT Id FROM Quote WHERE Name = 'Quote Test'];
        ChargentOrders__ChargentOrder__c newChargentOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c WHERE ChargentOrders__Account__c=: acc.Id ];
   
    	Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        //Fill input
        Map<String, Object> selectedMonthlyContributionDiscount = new Map<String,Object>();
        selectedMonthlyContributionDiscount.put('Recurrency', '2,3');
        Map<String, Object> bill =new Map<String, Object>();
        String datebill = Datetime.now().format('yyyy-MM-dd');
        bill.put('billingDatePlan', datebill);
        Double formulaCont = 093820283;
        bill.put('FormulaContributionAmount', formulaCont);
        bill.put('FormulaContributionAmountWithPromotions', 98989);

        inputMap.put('bill', bill);
        inputMap.put('selectedMonthlyContributionDiscount', selectedMonthlyContributionDiscount);
        inputMap.put('chargentOrderId', newChargentOrder.Id);
        inputMap.put('AssetId', ass.Id);
        inputMap.put('incomingQuoteId', qu.Id);

        OSH_ChargentOrders ins = new OSH_ChargentOrders();
        Boolean ret = ins.invokeMethod('createChargentOrders', inputMap, outMap, options);
        System.assertEquals(true, ret);
    }

    @isTest
    static void createChargentOrdersForeverTest5() {

        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Asset ass = [SELECT Id FROM Asset WHERE Name = 'AssetTest'];
        Quote qu = [SELECT Id FROM Quote WHERE Name = 'Quote Test'];
        ChargentOrders__ChargentOrder__c newChargentOrder = [SELECT Id FROM ChargentOrders__ChargentOrder__c WHERE ChargentOrders__Account__c=: acc.Id ];
   
    	Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        //Fill input
        Map<String, Object> selectedMonthlyContributionDiscount = new Map<String,Object>();
        selectedMonthlyContributionDiscount.put('Recurrency', 'Never');
        Map<String, Object> bill =new Map<String, Object>();
        String datebill = Datetime.now().format('yyyy-MM-dd');
        bill.put('billingDatePlan', datebill);
        Double formulaCont = 093820283;
        bill.put('FormulaContributionAmount', formulaCont);
        bill.put('FormulaContributionAmountWithPromotions', 98989);

        inputMap.put('bill', bill);
        inputMap.put('selectedMonthlyContributionDiscount', selectedMonthlyContributionDiscount);
        inputMap.put('chargentOrderId', newChargentOrder.Id);
        inputMap.put('AssetId', ass.Id);
        inputMap.put('incomingQuoteId', qu.Id);

        OSH_ChargentOrders ins = new OSH_ChargentOrders();
        Boolean ret = ins.invokeMethod('createChargentOrders', inputMap, outMap, options);
        System.assertEquals(true, ret);
    }
}