objects/ChargentOrders__Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ChargentOrders__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Charge</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRX-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChargentOrderUtilities.cls
global without sharing class ChargentOrderUtilities {
    @AuraEnabled 
    public static void voidTransaction(String transactionId){
    system.debug('voidTransaction executed');
    system.debug('parameters');
    //print parameter received
    system.debug('transactionId: ' + transactionId);
    //everything inside a try for troubleshoot
    try{
        //get chargent order transaction object
        ChargentOrders__Transaction__c chargentOrderTransaction = [SELECT Id, ChargentOrders__Type__c FROM ChargentOrders__Transaction__c WHERE Id=:transactionId];
        //update type to void
        chargentOrderTransaction.ChargentOrders__Type__c = 'Void';
        //update the record
        update chargentOrderTransaction;
    }catch(Exception e){
        system.debug(e);
    }
   }
   @AuraEnabled 
    public static void voidListOfTransactions(List<String> transactionIds){
    system.debug('voidTransaction executed');
    system.debug('parameters');
    //print parameter received
    system.debug('transactionIds: ' + transactionIds);
    //everything inside a try for troubleshoot
    try{
        // get all transactions based on the LIST received
        List<ChargentOrders__Transaction__c> chargentOrderTransactions = [SELECT Id, ChargentOrders__Type__c FROM ChargentOrders__Transaction__c WHERE Id IN:transactionIds];
        //for each and every chargent order transaction recived
        for(ChargentOrders__Transaction__c chargentOrderTransaction : chargentOrderTransactions){
            //update the type to void
            chargentOrderTransaction.ChargentOrders__Type__c = 'Void';
        }
        //update all transactions applicable based on the query [row 29]
        update chargentOrderTransactions;
    }catch(Exception e){
        system.debug(e);
    }
   }  
}