objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Age_Period_30d__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is foeld is necesary for the information package and Enroll process</description>
        <label>Age Period 30d</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Period_60d__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is necesary for Information Package and Enroll Process</description>
        <label>Age Period 60d</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agent_Label__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Label</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Agent Label)</relationshipLabel>
        <relationshipName>AgentLabel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enroller_Id__c</fullName>
        <label>Enroller Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information_Packet_Number__c</fullName>
        <label>Information Packet #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_MemBer_Based_Dob__c</fullName>
        <description>This Field is necesary for know the specific Dob and Verbiage in Information Package</description>
        <label>Old MemBer Based Dob</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is  a field for Infomation Package</description>
        <label>Price Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Rating Member)</relationshipLabel>
        <relationshipName>Rating_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Servicing_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Servicing Agent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Servicing Agent)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Writing_agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writing agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSHQuoteServiceTest.cls
@IsTest global class OSHQuoteServiceTest {
	//create Quote, Lead
	//input must have: "quoteId", "leadId", "informationPacketNumber", "addInfo30", "addInfo60", "oldestDOB",
	//"priceChange", "ratingMemberId", "quoteStatus", "quoteStatus", "writingAgent", "enrollerId", "agentLabel"
   
    @isTest static void testEncryptIfNecessary() {
    	Test.startTest(); 
    
        //create User
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        List<User> user1id = [SELECT Id FROM User LIMIT 1];
        
    	//create Account
        Account newAccount = new Account(
            LastName = 'testAccount'
        );
        insert newAccount;        
        System.debug('NEW ACCOUNT => ' + newAccount);    
        List<Account> account1id = [SELECT Id FROM Account LIMIT 1];
        
        //create Opportunity
        Opportunity newOpportunity = new Opportunity(
            Name = 'testOpportunity',
            StageName='Enrollment',
            CloseDate= Date.Today()
        );
        insert newOpportunity;        
        System.debug('NEW OPPORTUNITY => ' + newOpportunity);
        List<Opportunity> opportunity1id = [SELECT Id FROM Opportunity LIMIT 1];
        
        Date myDate = Date.newInstance(1990, 2, 17);
        
        //create Quote
        Quote newQuote = new Quote(
            Name = 'testQuote',
            OpportunityId = opportunity1id[0].Id,
            Servicing_Agent__c = account1id[0].Id,
            Writing_agent__c = user1id[0].Id,
            Enroller_Id__c = user1id[0].Id,
            Agent_Label__c = account1id[0].Id,
            Age_Period_30d__c = false,
            Age_Period_60d__c = false,
            Rating_Member__c = account1id[0].Id,
            Old_MemBer_Based_Dob__c = myDate,
            Price_Change__c = false,
            Status = 'Draft',
            Information_Packet_Number__c = '10000-84951'
        );
        insert newQuote;        
        System.debug('NEW QUOTE => ' + newQuote);
        List<Quote> quote1id = [SELECT Id FROM Quote LIMIT 1];
        
        //create Lead
        Lead newLead = new Lead(
            FirstName='LeadTestoDaio',
            LastName='LeadTestoDaio'
        );
        insert newLead;        
        System.debug('NEW LEAD => ' + newLead);  
        List<Lead> lead1id = [SELECT Id FROM Lead LIMIT 1];
        
        //create inputs
        String METHOD_NAME = 'updateQuoteAfterCreation';
        Map<String, Object> mapInput = new Map<String, Object> {
                'quoteId' => quote1id[0].Id,
                'leadId' => lead1id[0].Id,
                'informationPacketNumber' => '10000-00213',
                'addInfo30' => true,
                'addInfo60' => true,
				'oldestDOB' => '1994-12-12',
                'priceChange' => false,
                'ratingMemberId' => account1id[0].Id,
                'quoteStatus' => 'Presented',
                'servicingAgent' => account1id[0].Id,
                'writingAgent' => user1id[0].Id,
                'enrollerId' => user1id[0].Id,
                'agentLabel' => account1id[0].Id,
                'leadStatus' => 'New'
        }; 
        Map<String, Object> mapOutput = new Map<String, Object>();
        Map<String, Object> mapOptions = new Map<String, Object>();
        
        
        OSHQuoteService oshQuoteService = new OSHQuoteService();
        Boolean success = oshQuoteService.updateQuoteAfterCreation(mapInput, mapOutput, mapOptions);

     
        Test.stopTest(); 
         
        System.assertEquals(success, true);
    }
    
    
    @isTest static void testInvokeMethod() {
        Test.startTest(); 
    
        //create User
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
        List<User> user1id = [SELECT Id FROM User LIMIT 1];
        
    	//create Account
        Account newAccount = new Account(
            LastName = 'testAccount'
        );
        insert newAccount;        
        System.debug('NEW ACCOUNT => ' + newAccount);    
        List<Account> account1id = [SELECT Id FROM Account LIMIT 1];
        
        //create Opportunity
        Opportunity newOpportunity = new Opportunity(
            Name = 'testOpportunity',
            StageName='Enrollment',
            CloseDate= Date.Today()
        );
        insert newOpportunity;        
        System.debug('NEW OPPORTUNITY => ' + newOpportunity);
        List<Opportunity> opportunity1id = [SELECT Id FROM Opportunity LIMIT 1];
        
        Date myDate = Date.newInstance(1990, 2, 17);
        
        //create Quote
        Quote newQuote = new Quote(
            Name = 'testQuote',
            OpportunityId = opportunity1id[0].Id,
            Servicing_Agent__c = account1id[0].Id,
            Writing_agent__c = user1id[0].Id,
            Enroller_Id__c = user1id[0].Id,
            Agent_Label__c = account1id[0].Id,
            Age_Period_30d__c = false,
            Age_Period_60d__c = false,
            Rating_Member__c = account1id[0].Id,
            Old_MemBer_Based_Dob__c = myDate,
            Price_Change__c = false,
            Status = 'Draft',
            Information_Packet_Number__c = '10000-84951'
        );
        insert newQuote;        
        System.debug('NEW QUOTE => ' + newQuote);
        List<Quote> quote1id = [SELECT Id FROM Quote LIMIT 1];
        
        //create Lead
        Lead newLead = new Lead(
            FirstName='LeadTestoDaio',
            LastName='LeadTestoDaio'
        );
        insert newLead;        
        System.debug('NEW LEAD => ' + newLead);  
        List<Lead> lead1id = [SELECT Id FROM Lead LIMIT 1];
        
        //create inputs
        String METHOD_NAME = 'updateQuoteAfterCreation';
        Map<String, Object> mapInput = new Map<String, Object> {
                'quoteId' => quote1id[0].Id,
                'leadId' => lead1id[0].Id,
                'informationPacketNumber' => '10000-00213',
                'addInfo30' => true,
                'addInfo60' => true,
				'oldestDOB' => '1994-12-12',
                'priceChange' => false,
                'ratingMemberId' => account1id[0].Id,
                'quoteStatus' => 'Presented',
                'servicingAgent' => account1id[0].Id,
                'writingAgent' => user1id[0].Id,
                'enrollerId' => user1id[0].Id,
                'agentLabel' => account1id[0].Id,
                'leadStatus' => 'New'
        }; 
        Map<String, Object> mapOutput = new Map<String, Object>();
        Map<String, Object> mapOptions = new Map<String, Object>();
        
        
        OSHQuoteService oshQuoteService = new OSHQuoteService();
        Boolean success = oshQuoteService.invokeMethod(METHOD_NAME, mapInput, mapOutput, mapOptions);

     
        Test.stopTest(); 
         
        System.assertEquals(success, true);
        
    }
    
    
}