objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Age_Period_30d__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is foeld is necesary for the information package and Enroll process</description>
        <label>Age Period 30d</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age_Period_60d__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is necesary for Information Package and Enroll Process</description>
        <label>Age Period 60d</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agent_Label__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent Label</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Agent Label)</relationshipLabel>
        <relationshipName>AgentLabel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enroller_Id__c</fullName>
        <label>Enroller Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information_Packet_Number__c</fullName>
        <label>Information Packet #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Old_MemBer_Based_Dob__c</fullName>
        <description>This Field is necesary for know the specific Dob and Verbiage in Information Package</description>
        <label>Old MemBer Based Dob</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is  a field for Infomation Package</description>
        <label>Price Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rating Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Rating Member)</relationshipLabel>
        <relationshipName>Rating_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Servicing_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Servicing Agent</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Servicing Agent)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Writing_agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writing agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__EffectiveDate__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OSHQuoteService.cls
global without sharing class OSHQuoteService implements vlocity_ins.VlocityOpenInterface2{
    public Boolean invokeMethod(String methodName, Map<String, Object> inputs, Map<String, Object> outputs, Map<String, Object> options){
        try {
            if (methodName == 'updateQuoteAfterCreation') {
                system.debug('inside updateQuoteAfterCreation');
                return updateQuoteAfterCreation(inputs, outputs, options);
            }
        } catch (Exception e) {
            outputs.put('Error', e.getMessage());
            outputs.put('ErrorLine', e.getLineNumber());
            outputs.put('ErrorType', e.getTypeName());
            outputs.put('MethodName', methodName);
        }
         return false;
    }

    
    @TestVisible private Boolean updateQuoteAfterCreation(Map<String,Object> inputs, Map<String,Object> outputs, Map<String,Object> options){
        for(String key : inputs.keySet()){
            system.debug('key: ' + key + ' value: ' + inputs.get(key));
        }
        String quoteId = (String)inputs.get('quoteId');
        Quote quote = [SELECT Id, Servicing_Agent__c, Writing_agent__c, Enroller_Id__c, Agent_Label__c, Age_Period_30d__c, vlocity_ins__EffectiveDate__c,
                        Age_Period_60d__c, Rating_Member__c, Old_MemBer_Based_Dob__c, Price_Change__c, Status, Information_Packet_Number__c
                        FROM Quote 
                        WHERE Id =: quoteId];
        System.debug(quote);                        
        quote.Information_Packet_Number__c = (String)inputs.get('informationPacketNumber');
        quote.Age_Period_30d__c = String.valueOf(inputs.get('addInfo30')) != '' ? (Boolean)inputs.get('addInfo30') : false;
        quote.Age_Period_60d__c = String.valueOF(inputs.get('addInfo60')) != '' ? (Boolean)inputs.get('addInfo60') : false;

        List<String> dateList = String.valueOF(inputs.get('oldestDOB')).split('-');
        Date memberDOB = date.parse(dateList.get(1)+'/'+dateList.get(2)+'/'+dateList.get(0));
        quote.Old_MemBer_Based_Dob__c =  memberDOB;
        List<String> dateList2 = String.valueOF(inputs.get('effectiveDate')).split('-');
        Date memberEffectiveDate = date.parse(dateList2.get(1)+'/'+dateList2.get(2)+'/'+dateList2.get(0));
        quote.vlocity_ins__EffectiveDate__c = memberEffectiveDate;
        quote.Price_Change__c = (Boolean)inputs.get('priceChange');
        quote.Rating_Member__c = (String)inputs.get('ratingMemberId');
        quote.Status = (String)inputs.get('quoteStatus');
        quote.Servicing_Agent__c = (String)inputs.get('servicingAgent');
        quote.Writing_agent__c = (String)inputs.get('writingAgent');
        quote.Enroller_Id__c = (String)inputs.get('enrollerId');
        quote.Agent_Label__c = (String)inputs.get('agentLabel');
        update quote;
        system.debug('updatedQuote' + quote);
        String leadId = (String)inputs.get('leadId');
        Lead lead = [SELECT Id, Status FROM Lead WHERE Id = :leadId];
        lead.Status = (String)inputs.get('leadStatus');
        update lead;
        system.debug('updatedLead' + lead);
        return true;
    }
}